export const eventName = {
  "하단바 상담신청 팝업 이벤트": "A_sign_up_popup",
  "하단바 상담신청 이벤트": "A_sign_up",
  "하단바 상담신청 시도 이벤트": "A_sign_up_try",
  "하단바 날짜 시간 이벤트": "A_date_time",
  "하단바 날짜 이벤트": "A_date",
  "하단바 시간 이벤트": "A_time",
  "하단바 상담내용 이벤트": "A_counsult_content",
  "하단바 혼인형태 이벤트": "A_marriage_types",
  "하단바 미성년자녀 이벤트": "A_children_with",
  "하단바 전화상담 이벤트": "A_call",
  "하단바 전화상담 시도 이벤트": "A_call_try",
  "하단바 카카오채팅 이벤트": "A_kakao",
  "하단바 카카오채팅 시도 이벤트": "A_kakao_try",
  "메인페이지 상담신청 팝업 이벤트": "B_sign_up_popup",
  "메인페이지 상담신청 이벤트": "B_sign_up",
  "메인페이지 상담신청 시도 이벤트": "B_sign_up_try",
  "메인페이지 날짜 시간 이벤트": "B_date_time",
  "메인페이지 날짜 이벤트": "B_date",
  "메인페이지 시간 이벤트": "B_time",
  "메인페이지 상담내용 이벤트": "B_counsult_content",
  "메인페이지 혼인형태 이벤트": "B_marriage_types",
  "메인페이지 미성년자녀 이벤트": "B_children_with",
  "메인페이지 전화상담 이벤트": "B_call",
  "메인페이지 전화상담 시도 이벤트": "B_call_try",
  "메인페이지 카카오채팅 이벤트": "B_kakao",
  "메인페이지 카카오채팅 시도 이벤트": "B_kakao_try",
  "다시만나기 상담신청 팝업 이벤트": "C_sign_up_popup",
  "다시만나기 상담신청 이벤트": "C_sign_up",
  "다시만나기 상담신청 시도 이벤트": "C_sign_up_try",
  "다시만나기 날짜 시간 이벤트": "C_date_time",
  "다시만나기 날짜 이벤트": "C_date",
  "다시만나기 시간 이벤트": "C_time",
  "다시만나기 상담내용 이벤트": "C_counsult_content",
  "다시만나기 혼인형태 이벤트": "C_marriage_types",
  "다시만나기 미성년자녀 이벤트": "C_children_with",
  "다시만나기 전화상담 이벤트": "C_call",
  "다시만나기 전화상담 시도 이벤트": "C_call_try",
  "다시만나기 카카오채팅 이벤트": "C_kakao",
  "다시만나기 카카오채팅 시도 이벤트": "C_kakao_try",
};
